apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app-deployment  # Tên của Deployment mà HPA sẽ quản lý
  minReplicas: 1  # Số lượng pod tối thiểu
  maxReplicas: 5  # Số lượng pod tối đa
  metrics:
  - type: Resource
    resource:
      name: cpu  # Bạn cũng có thể sử dụng memory thay vì cpu
      target:
        type: Utilization
        averageUtilization: 50  # Mở rộng khi sử dụng CPU hơn 50%

